name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run tests
        run: go test -v ./... -exclude=./templates/...

      - name: Check Go formatting
        run: |
          if [ "$(gofmt -s -l . | grep -v '^templates/' | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted:"
            gofmt -s -l . | grep -v '^templates/'
            exit 1
          fi

      - name: Run go vet
        run: go vet ./... -exclude=./templates/...

      - name: Run go mod verify
        run: go mod verify

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser (build only)
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: build --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }} 